Repository sepandhaghighi/pycm, pull requests merged in 2022-03, with the labels that each got.

#425 Coc update
  .github/CODE_OF_CONDUCT.md
  .github/workflows/test.yml
  CHANGELOG.md
  dev-requirements.txt
Labels: Document

#426 Anaconda workflow
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  CHANGELOG.md
  Otherfiles/meta.yaml
  Otherfiles/version_check.py
Labels: test

#428 Iterating/Casting
  CHANGELOG.md
  Document/Document.ipynb
  Test/overall_test.py
  pycm/pycm_obj.py
Labels: enhancement
