Repository sepandhaghighi/pycm, pull requests merged in 2022-08, with the labels that each got.

#443 Hamming Distance
  CHANGELOG.md
  Document/Document.ipynb
  README.md
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/verified_test.py
  Test/warning_test.py
  pycm/pycm_class_func.py
  pycm/pycm_handler.py
  pycm/pycm_obj.py
  pycm/pycm_param.py
Labels: enhancement, new feature, nlnet

#444 Braun-Blanquet similarity
  CHANGELOG.md
  Document/Document.ipynb
  README.md
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/verified_test.py
  Test/warning_test.py
  pycm/pycm_class_func.py
  pycm/pycm_handler.py
  pycm/pycm_param.py
Labels: enhancement, new feature, nlnet

#445 Readme
  CHANGELOG.md
  README.md
Labels: Document

#446 Doc HTML
  Document/Document.ipynb
  Otherfiles/doc_run.bat
  Otherfiles/doc_to_html.bat
Labels: Document

#447 Version 3.6
  .github/CODE_OF_CONDUCT.md
  .github/FUNDING.yml
  CHANGELOG.md
  CITATION.cff
  Document/Document.ipynb
  Document/Document_Files/cm1.csv
  Document/Document_Files/cm1.html
  Document/Document_Files/cm1.obj
  Document/Document_Files/cm1.pycm
  Document/Document_Files/cm1_colored.html
  Document/Document_Files/cm1_colored2.html
  Document/Document_Files/cm1_filtered.html
  Document/Document_Files/cm1_filtered2.html
  Document/Document_Files/cm1_header.csv
  Document/Document_Files/cm1_no_vectors.obj
  Document/Document_Files/cm1_normalized.html
  Document/Document_Files/cm1_stat.obj
  Document/Document_Files/cm1_summary.html
  Document/Example1.ipynb
  Document/Example1_Files/cm1.html
  Document/Example1_Files/cm2.html
  Document/Example1_Files/cm3.html
  Document/Example2.ipynb
  Document/Example3.ipynb
  Document/Example4.ipynb
  Document/Example4_Files/cm.obj
  Document/Example4_Files/cm_no_vectors.obj
  Document/Example4_Files/cm_stat.obj
  Document/Example5.ipynb
  Document/Example6.ipynb
  Document/Example7.ipynb
  Document/Example8.ipynb
  Document/README.md
  Otherfiles/NGIAssure.svg
  Otherfiles/NlNet.svg
  Otherfiles/doc_run.bat
  Otherfiles/doc_to_html.bat
  Otherfiles/meta.yaml
  Otherfiles/test.csv
  Otherfiles/test.html
  Otherfiles/test.obj
  Otherfiles/test.pycm
  Otherfiles/version_check.py
  README.md
  Test/error_test.py
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/verified_test.py
  Test/warning_test.py
  dev-requirements.txt
  pycm/pycm_class_func.py
  pycm/pycm_handler.py
  pycm/pycm_obj.py
  pycm/pycm_output.py
  pycm/pycm_param.py
  pycm/pycm_util.py
  setup.py
Labels: release, nlnet

#452 Performance
  CHANGELOG.md
  pycm/pycm_profile.py
  pycm/pycm_util.py
Labels: performance

#453 Reference Section Removed from README.md
  .github/CONTRIBUTING.md
  CHANGELOG.md
  README.md
Labels: enhancement
