Repository sepandhaghighi/pycm, pull requests merged in 2023-01, with the labels that each got.

#475 Distance/Similarity
  CHANGELOG.md
  Document/Distance.ipynb
  Document/Document.ipynb
  Document/README.md
  Otherfiles/notebook_check.py
  Test/error_test.py
  Test/function_test.py
  Test/verified_test.py
  pycm/__init__.py
  pycm/pycm_curve.py
  pycm/pycm_distance.py
  pycm/pycm_obj.py
  pycm/pycm_param.py
Labels: enhancement, new feature, nlnet

#476 New Minor Features
  CHANGELOG.md
  Document/Document.ipynb
  Test/overall_test.py
  pycm/pycm_obj.py
Labels: enhancement

#477 Test
  CHANGELOG.md
  Test/compare_test.py
  Test/function_test.py
  pycm/pycm_output.py
Labels: test

#478 doc_to_html update
  Otherfiles/doc_to_html.bat
Labels: enhancement

#479 Compare
  CHANGELOG.md
  Document/Document.ipynb
  README.md
  Test/compare_test.py
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/warning_test.py
  pycm/pycm_compare.py
  pycm/pycm_handler.py
  pycm/pycm_interpret.py
  pycm/pycm_output.py
  pycm/pycm_overall_func.py
  pycm/pycm_param.py
  pycm/pycm_util.py
Labels: enhancement, nlnet

#480 Relabel Bug Fixed
  CHANGELOG.md
  Test/overall_test.py
  pycm/pycm_obj.py
Labels: bug, nlnet
