Repository sepandhaghighi/pycm, pull requests merged in 2023-12, with the labels that each got.

#526 Issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  Otherfiles/RELEASE.md
  Otherfiles/version_check.py
Labels: enhancement, Document, stale

#527 Issue template problem
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: bug, Document

#528 Python 3.12
  .github/workflows/test.yml
  CHANGELOG.md
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/verified_test.py
  setup.py
Labels: test, major

#529 Minor edits
  Otherfiles/version_check.py
  autopep8.bat
  autopep8.sh
  pycm/pycm_class_func.py
  pycm/pycm_compare.py
  pycm/pycm_handler.py
  pycm/pycm_obj.py
  pycm/pycm_output.py
  pycm/pycm_overall_func.py
  pycm/pycm_param.py
  pycm/pycm_util.py
Labels: refactoring, minor
