Repository sepandhaghighi/pycm, pull requests merged in 2023-04, with the labels that each got.

#490 Metrics off
  CHANGELOG.md
  Document/Document.ipynb
  README.md
  Test/error_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/plot_test.py
  pycm/pycm_compare.py
  pycm/pycm_handler.py
  pycm/pycm_obj.py
  pycm/pycm_param.py
  pycm/pycm_util.py
Labels: enhancement, performance, nlnet

#491 NPV Micro/Macro
  CHANGELOG.md
  Document/Document.ipynb
  Test/function_test.py
  Test/output_test.py
  Test/overall_test.py
  Test/warning_test.py
  pycm/pycm_handler.py
  pycm/pycm_overall_func.py
  pycm/pycm_param.py
Labels: enhancement, new feature, nlnet

#493 Codecov
  .github/workflows/test.yml
  CHANGELOG.md
  dev-requirements.txt
Labels: dependencies, test

#494 Doctests bug in `pytest` fixed
  .github/workflows/test.yml
  Test/output_test.py
  pycm/pycm_compare.py
  pycm/pycm_curve.py
  pycm/pycm_distance.py
  pytest.ini
Labels: bug, enhancement, Document, test

#500 Log loss
  CHANGELOG.md
  Document/Document.ipynb
  Test/error_test.py
  Test/function_test.py
  Test/verified_test.py
  pycm/pycm_obj.py
  pycm/pycm_overall_func.py
  pycm/pycm_param.py
Labels: enhancement, new feature, nlnet
