Repository sepandhaghighi/pycm, pull requests merged in 2024-10, with the labels that each got.

#558 Some distance metrics added
  CHANGELOG.md
  Document/Distance.ipynb
  Otherfiles/notebook_to_html.py
  Test/verified_test.py
  pycm/pycm_distance.py
  pycm/pycm_param.py
Labels: enhancement, new feature

#560 Refactor
  .coveragerc
  .github/CONTRIBUTING.md
  .github/workflows/test.yml
  CHANGELOG.md
  Otherfiles/RELEASE.md
  Otherfiles/version_check.py
  Test/error_test.py
  Test/function_test.py
  Test/overall_test.py
  Test/plot_error_test.py
  Test/plot_test.py
  Test/verified_test.py
  Test/warning_test.py
  pycm/__init__.py
  pycm/__main__.py
  pycm/basic_test.py
  pycm/ci.py
  pycm/class_funcs.py
  pycm/cm.py
  pycm/compare.py
  pycm/curve.py
  pycm/distance.py
  pycm/errors.py
  pycm/handlers.py
  pycm/interpret.py
  pycm/multilabel_cm.py
  pycm/output.py
  pycm/overall_funcs.py
  pycm/params.py
  pycm/profile.py
  pycm/utils.py
Labels: refactoring

#561 Minor edits
  Document/Distance.ipynb
  Otherfiles/RELEASE.md
  README.md
Labels: Document, minor

#562 Python 3.13
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: Document, test

#563 Version 4.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  CHANGELOG.md
  Document/Document.ipynb
  Document/Document_files/cm1.html
  Document/Document_files/cm1.obj
  Document/Document_files/cm1_colored.html
  Document/Document_files/cm1_colored2.html
  Document/Document_files/cm1_filtered.html
  Document/Document_files/cm1_filtered2.html
  Document/Document_files/cm1_no_vectors.obj
  Document/Document_files/cm1_normalized.html
  Document/Document_files/cm1_stat.obj
  Document/Document_files/cm1_summary.html
  Document/Example1.ipynb
  Document/Example1_files/cm1.html
  Document/Example1_files/cm2.html
  Document/Example1_files/cm3.html
  Document/Example2.ipynb
  Document/Example4.ipynb
  Document/Example4_files/cm.obj
  Document/Example4_files/cm_no_vectors.obj
  Document/Example4_files/cm_stat.obj
  Document/Example6.ipynb
  Document/Example7.ipynb
  Document/Example8.ipynb
  Otherfiles/meta.yaml
  Otherfiles/test.html
  Otherfiles/test.obj
  Otherfiles/version_check.py
  README.md
  SECURITY.md
  pycm/params.py
  setup.py
Labels: release

#567 Website v4.1
  doc/Distance.html
  doc/Document_files/Document_141_1.png
  doc/Document_files/Document_142_1.png
  doc/Document_files/Document_143_1.png
  doc/Document_files/Document_144_1.png
  doc/Document_files/Document_145_1.png
  doc/Document_files/Document_146_1.png
  doc/Document_files/Document_197_1.png
  doc/Document_files/Document_202_1.png
  doc/Document_files/cm1.html
  doc/Document_files/cm1.obj
  doc/Document_files/cm1_colored.html
  doc/Document_files/cm1_colored2.html
  doc/Document_files/cm1_filtered.html
  doc/Document_files/cm1_filtered2.html
  doc/Document_files/cm1_no_vectors.obj
  doc/Document_files/cm1_normalized.html
  doc/Document_files/cm1_stat.obj
  doc/Document_files/cm1_summary.html
  doc/Example1.html
  doc/Example1_files/cm1.html
  doc/Example1_files/cm2.html
  doc/Example1_files/cm3.html
  doc/Example2.html
  doc/Example3.html
  doc/Example4.html
  doc/Example4_files/cm.obj
  doc/Example4_files/cm_no_vectors.obj
  doc/Example4_files/cm_stat.obj
  doc/Example6.html
  doc/Example7.html
  doc/Example8.html
  doc/index.html
  donate.html
  download.html
  index.html
  test.html
Labels: website

#568 Diagrams
  images/block_diagram.jpg
  images/compare_block_diagram.jpg
  images/recommendation_block_diagram.jpg
Labels: website

#569 Add/limit gh action run
  .github/workflows/test.yml
  CHANGELOG.md
Labels: test
