Repository sepandhaghighi/pycm, pull requests merged in 2025-01, with the labels that each got.

#585 Update/actions version
  .github/workflows/publish_conda.yaml
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
Labels: dependencies, test

#586 Version 4.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  Document/Document.ipynb
  Document/Document_files/cm1.html
  Document/Document_files/cm1.obj
  Document/Document_files/cm1_colored.html
  Document/Document_files/cm1_colored2.html
  Document/Document_files/cm1_filtered.html
  Document/Document_files/cm1_filtered2.html
  Document/Document_files/cm1_no_vectors.obj
  Document/Document_files/cm1_normalized.html
  Document/Document_files/cm1_stat.obj
  Document/Document_files/cm1_summary.html
  Document/Example1_files/cm1.html
  Document/Example1_files/cm2.html
  Document/Example1_files/cm3.html
  Document/Example4.ipynb
  Document/Example4_files/cm.obj
  Document/Example4_files/cm_no_vectors.obj
  Document/Example4_files/cm_stat.obj
  Document/Example6.ipynb
  Otherfiles/meta.yaml
  Otherfiles/test.html
  Otherfiles/test.obj
  Otherfiles/version_check.py
  README.md
  SECURITY.md
  pycm/params.py
  setup.py
Labels: release

#587 Website v4.2
  doc/Distance.html
  doc/Document_files/cm1.html
  doc/Document_files/cm1.obj
  doc/Document_files/cm1_colored.html
  doc/Document_files/cm1_colored2.html
  doc/Document_files/cm1_filtered.html
  doc/Document_files/cm1_filtered2.html
  doc/Document_files/cm1_no_vectors.obj
  doc/Document_files/cm1_normalized.html
  doc/Document_files/cm1_stat.obj
  doc/Document_files/cm1_summary.html
  doc/Example1_files/cm1.html
  doc/Example1_files/cm2.html
  doc/Example1_files/cm3.html
  doc/Example4.html
  doc/Example4_files/cm.obj
  doc/Example4_files/cm_no_vectors.obj
  doc/Example4_files/cm_stat.obj
  doc/Example6.html
  doc/index.html
  donate.html
  download.html
  index.html
  test.html
Labels: website

#588 Cite
  CHANGELOG.md
  README.md
Labels: Document
